### PR TITLE
Update Localizable.strings

### PR DESCRIPTION
**Pull request by t0mi**

### CODE REVIEW

**Comment by SparkDev97** [comment]
Nice one! Thanks!

**Comment by t0mi** [comment]
Localisation in the Snowboard Application would also be great.  It's only in English at the moment.
A empty „de.lproj“ in the „SnowBoard.app“ would be enough to localise the App to German. 
Thanks in advance.

**Comment by SparkDev97** [comment]
They should carry over from here, I will check and fix it if not though.

**Comment by t0mi** [comment]
96706F43-772F-4E3E-9EF8-C4D4B1EE7683

It’s English for me and all of my friends. But if I create an empty de.lproj folder in /Applications/SnowBoard.app/ it works fine.

**Pull request merged**
